### ISSUE TITLE
Error POST url on Linux

### ISSUE THREAD

**Issue by kristofvanwoensel** [lino-framework/eidreader#10]
The beid POST link works fine on windows, but not on Linux.

Log writes:
INFO POST data to beid://http//localhost:4000/eid  

while it should be http//:localhost:4000/eid   (beid:// should be dropped, colon should be added after http)

**Comment by lsaffre** [comment]
Thanks for reporting. I don't live in Belgium and my eid card seems to be broken (even eid-viewer doesn't work) so I am currently a bit stuck with reproducing this. But I guess that the problem is in the custom URL scheme handler. Try using a beid.sh file as described in https://eidreader.lino-framework.org/install.html

**Comment by kristofvanwoensel** [comment]
I hardcoded my URL in the main.py file, so for testing it works.
I guess the code removes the colon instead of "beid://".

**Comment by lsaffre** [comment]
I now installed eidreader on my computer (Úbuntu 22.04) and tested with a new eid card. Everything works fine for me. So I cannot reproduce your problem.

**Comment by lsaffre** [comment]
Now after #13 we can assume that this was a duplicate. Solution is to [quote](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) the url so that the browser doesn't try to protect your users against an unsecure link, and to use eidreader 1.0.8 or later.
