### ISSUE TITLE
lib issue on mac os

### ISSUE THREAD

**Issue by ghost** [lino-framework/eidreader#3]
Hello there !

I'm having the following issue on mac os :

`eidreader
src/dyn_unix.c:34:SYS_dyn_LoadLibrary() dlopen(beidpkcs11.dll, 2): image not found
Traceback (most recent call last):
  File "/usr/local/bin/eidreader", line 3, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/eidreader/main.py", line 220, in main
    print(json.dumps(eid2dict()))
  File "/usr/local/lib/python3.7/site-packages/eidreader/main.py", line 90, in eid2dict
    pkcs11.load()
  File "/usr/local/lib/python3.7/site-packages/PyKCS11/__init__.py", line 483, in load
    raise PyKCS11Error(-1, pkcs11dll_filename)
PyKCS11.PyKCS11Error: Load (beidpkcs11.dll)
`

**Comment by lsaffre** [comment]
Yes, I believe that it doesn't work on MacOS. You are the first Mac user who tries it. The problem is here:
https://github.com/lino-framework/eidreader/blob/master/eidreader/main.py#L84
IOW you must find out the name of the file which contains the Python KCS11 library and then set an environment variable PYKCS11LIB to that name.  And if you post the name here, I can adapt the code so that future Mac users don't stumble into the problem. After reading [this](https://github.com/OpenSC/OpenSC/wiki/macOS-Quick-Start) I guess that "PYKCS11LIB=opensc-pkcs11.so" should do the trick. Please confirm whether it works.

**Comment by ghost** [comment]
Thanks for the fast answer 👍 

The Belgian EID middleware installs the lib there :

`/usr/local/lib/beid-pkcs11.bundle/Contents/MacOS/`

The name of the file is :

`libbeidpkcs11.dylib`

Edit:

I've added the correct path to PYKCS11LIB and it seems to work just fine now.
